/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class traffix_NativeUtils */

#ifndef _Included_traffix_NativeUtils
#define _Included_traffix_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     traffix_NativeUtils
 * Method:    Win_LoadCursorFromFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_traffix_NativeUtils_Win_1LoadCursorFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     traffix_NativeUtils
 * Method:    clock
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_traffix_NativeUtils_clock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
